In [1]:
from sklearn.cross_validation import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn import tree 
#from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing

C:\Users\Shewit Bolt\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
import pandas as pd 
#import numpy as np

In [3]:
#import pandas as pd 
datasets = pd.read_csv('playTennis.csv')
datasets

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [4]:
ab=preprocessing.LabelEncoder()
datasets=datasets.apply(ab.fit_transform)
datasets

    Outlook  Temperature  Humidity  Wind  Play Tennis
0         2            1         0     1            0
1         2            1         0     0            0
2         0            1         0     1            1
3         1            2         0     1            1
4         1            0         1     1            1
5         1            0         1     0            0
6         0            0         1     0            1
7         2            2         0     1            0
8         2            0         1     1            1
9         1            2         1     1            1
10        2            2         1     0            1
11        0            2         0     0            1
12        0            1         1     1            1
13        1            2         0     0            0

In [5]:
#split dataset in to featurs and target variables
feature_cols=['Outlook','Temperature', 'Humidity','Wind']
X = datasets[feature_cols] # Features
Y = datasets.Play # Target variable
X

AttributeError: 'DataFrame' object has no attribute 'Play'

In [ ]:
Y

In [ ]:
##split dataset in to train set and test set
X_train, X_test , Y_train,Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 100)

In [ ]:
X_train

In [ ]:
Y_train

In [ ]:
X_test

In [ ]:
Y_test

In [ ]:
# cerat descision tree classifeir object--clf
clf_entropy = DecisionTreeClassifier(criterion='entropy')
clf_entropy.fit(X_train.astype(int),Y_train.astype(int)) 
Y_pred_en = clf_entropy.predict(X_test)

Y_pred_en

In [ ]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy is :{0}".format(accuracy_score(Y_test.astype(int),Y_pred_en) * 100))

In [ ]:
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO
from IPython.display import Image
import pydotplus
dot_file=StringIO()
export_graphviz(clf_entropy, out_file=dot_file,filled=True, rounded=True,special_characters=True)
graph = pydotplus.graph_from_dot_file(dot_file.getvalue())  
graph.write_png('playTennis.png')
Image(graph.create_png())